export enum ViewType{
    BAR_GRAPH,GRAPH,LIST,GRID,IMAGE
}
export enum FilterViewType{
    HIDE,HIGHLIGHT,CLASSIFY
}
export enum FilterType{
    NONE,DIRECTOR,FRANCHISE,COUNTRY,IN_YEAR,UNTIL_YEAR,MONTH,ACTOR,COMPANY,
}
export enum SortType{
    WW_GROSS,DM_GROSS,INTL_GROSS,BUDGET,RELEASE,RATING_IMDB,RATING_META,RUNNING_TIME,
    DM_GROSS_RATIO,NONE
}